# Generated by Django 4.1.12 on 2023-10-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiLogging",
            fields=[
                (
                    "_id",
                    models.CharField(
                        editable=False, max_length=24, primary_key=True, serialize=False
                    ),
                ),
                ("entityCode", models.CharField(max_length=255)),
                ("appStoreCode", models.CharField(max_length=10)),
                ("apiEndpoint", models.CharField(max_length=255)),
                ("payload", models.TextField()),
                ("response", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hb_api_logging",
            },
        ),
        migrations.CreateModel(
            name="HbAppStoreEntityMapping",
            fields=[
                (
                    "_id",
                    models.CharField(
                        editable=False, max_length=24, primary_key=True, serialize=False
                    ),
                ),
                ("entityCode", models.CharField(max_length=255)),
                ("appStoreCode", models.CharField(max_length=10)),
                ("apiKey", models.CharField(max_length=255)),
                ("apiSecret", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hb_app_store_entity_mapping",
            },
        ),
        migrations.CreateModel(
            name="HbAppStoreMaster",
            fields=[
                (
                    "_id",
                    models.CharField(
                        editable=False, max_length=24, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("rating", models.CharField(max_length=10)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hb_app_store_master",
            },
        ),
    ]
