# Generated by Django 4.1.13 on 2023-11-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0002_instance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
