# Generated by Django 4.1.12 on 2023-10-19 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientDetail",
            fields=[
                (
                    "_id",
                    models.CharField(
                        editable=False, max_length=24, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=15)),
                (
                    "apiKey",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("reqCount", models.IntegerField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("isActive", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "hb_client_details",
            },
        ),
        migrations.CreateModel(
            name="HbApplications",
            fields=[
                (
                    "_id",
                    models.CharField(
                        editable=False, max_length=24, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hb_applications",
            },
        ),
    ]
